name: chemvae
channels:
  - rdkit
  - conda-forge

dependencies:
  - keras=2.0.6
  - tensorflow-gpu=1.1.0
  - h5py
  - hdf5
  - pandas=0.19.2
  - python=3
  - scikit-learn
  - boost
  - rdkit
  - yaml
  - numpy
  - matplotlib



